0. Open
1. Review
2. Topic
    
    2.1 피드 포워드 신경망 언어 모델(Neural Network Language Model, NNML)
    
    2.2 순환 신경망 언어 모델(Recurrent Neural Network Language Model, RNNLM)
    
    2.3 RNN 이용 텍스트 생성
    
    2.4 글자 단위 RNN (Char RNN)
    
3. Q & A
4. Next
5. Close

- 피드 포워드 신경망 언어 모델 (Neural Network Language Model, NNLM)

- 언어 모델은 문장에 확률을 할당하는 모델
- 주어진 문맥으로 부터 아직 모르는 단어를 예측하는 것을 언어 모델링이라 함
- 이전 단어를 이용해서 다음 단어를 예측하는 언어 모델링
- 통계적 언어 모델(Statistical Language Model, SLM) : n-gram 언어 모델
- 신경망 언어 모델(Neural Network Language Model, NNLM) : FFNN 언어 모델, RNN 언어 모델

#### n-gram 언어 모델

- 4-gram 언어 모델

An adorable little boy is spreading [예측 단어]

(An adorable little) -> 무시

[boy is spreading] -> 단어 예측에 사용, (n-1)개의 단어

P([w] | boy is spreading) = count(boy is spreading [w]) / count(boy is spreading)

corpus -> boy is spreading : 1000번 출현  
boy is spreading insults : 500번 출현, boy is spreading smiles : 200번 출현

P([insults] | boy is spreading) : 0.5  
P([smiles] | boy is spreading) : 0.2

n-gram 단점 : 희소 문제(sparsity probelm) -> 언어 모델에서 학습하지 않는 대상에 대해서는 확률이 0이기 때문에 예측하지 못하는 문제가 존재

- 희소 문제는 단어에 대한 유사도를 알 수 있다면 해결할 수 있다.
- 언어 모델이 단어의 유사도를 학습할 수 있도록 설계한다면, corpus에 없는 단어 시퀀스에 대한 예측이라도 유사한 단어가 사용된 단어 시퀀스를 참고하여 보다 정확한 예측을 할 수 있을 것이다.-> NNLM

#### 피드 포워드 신경망 및 언어 모델(NNLM)
- 언어 모델은 주어진 단어 시퀀스로부터 다음 단어를 예측하는 모델

예문 : "what will the fat cat sit on"

- 훈련 과정에서 "what will the fat cat"이라는 단어 시퀀스가 입력으로 주어지면 '다음 단어 "sit"을 예측하는 방식으로 훈련


- NNLM도 n-gram LM과 유사하게 다음 단어를 예측할 때, 앞의 모든 단어를 참고하는 것이 아니라 정해진 n개의 단어만을 참고한다.
- 예측을 할 때 정해지는 n개의 범위를 window라고 한다.

- 투사층(Projection Layer) : NNLM의 은닉층에 해당, 활성화 함수를 적용하지 않는다. 선형 함수 형태, lookup table

- NNLM의 이점 : 충분한 양의 훈련 corpus를 NNLM 모델을 통해 학습한다면 결과적으로 수많은 문장에서 유사한 목적으로 사용되는 단어들은 결국 유사한 임베딩 벡터값을 얻게 된다.
- NNLM의 단점 : 고정된 길이의 입력에 대한 예측만 가능하다. 윈도우 크기에 따라 학습을 수행하기 때문에 윈도우에 포함되지 않는 단어들을 참고할 수 없다는 문제

### RNN 언어 모델(Recurrent Neural Network Language Model, RNNLM)

- n-gram 언어 모델이나 NNLM은 고정된 개수의 단어만을 입력으로 받아야하는 단점
- 시점(time step)이라는 개념이 도입된 RNN으로 언어 모델을 만들면 입력의 길이를 고정하지 않을 수 있다.

- RNNLM은 기본적으로 예측 과정에서 이전 시점의 출력을 현재 시점의 입력으로 한다.
- RNNLM의 학습 방법(훈련 기법)은 교사 강요(teacher forcing) 방법을 사용한다.
- 교사 강요(teacher forcing) : 테스트 과정에서 t 시점의 출력이 t + 1 시점의 입력으로 사용되는 RNN 모델을 훈련시킬 때 사용하는 훈련 기법, 훈련할 때 교사 강요를 사용할 경우, 모델이 t 시점에서 예측한 값을 t + 1 시점에 입력으로 사용하지 않고, t 시점의 레이블, 즉 실제 알고있는 정답을 t + 1 시점의 입력으로 사용한다.

## RNN을 이용한 텍스트 생성
- 다대일(many-to-one) 구조의 RNN을 사용하여 문맥을 반영하여 텍스트를 생성하는 모델

- 문장 : '경마장에 있는 말은 뛰고 있다.', '그의 말이 법이다.', '가는 말이 고와야 오는 말이 곱다'
- 모델이 문맥을 학습할 수 있도록 전체 문장의 앞 단어들을 전부 고려하여 학습할 때  데이터를 재구성

|samples|x|y|
|---|---|---|
|1|경마장에|있는|
|2|경마장에 있는|말이|
|3|경마장에 있는 말이|뛰고|
|4|경마장에 있는 말이 뛰고||있다|
|5|그의|말이|
|6|그의 말이|법이다|
|7|가는|말이|
|8|가는 말이|고와야|
|9|가는 말이 고와야|오는|
|10|가는 말이 고와야 오는|말이|
|11|가는 말이 고와야 오는 말이|곱다|

In [1]:
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.utils import to_categorical

### 1. 데이터 이해/전처리

In [2]:
text = """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n
"""

In [3]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : {}'.format(vocab_size))

단어 집합의 크기 : 12


In [4]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [5]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i + 1]
        sequences.append(sequence)
        
print('학습에 사용할 샘플의 개수 : {:d}'.format(len(sequences)))

학습에 사용할 샘플의 개수 : 11


In [6]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [7]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [8]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [9]:
sequences = np.array(sequences)
X = sequences[ :, :-1]
y = sequences[ :, -1]

In [10]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [11]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [12]:
y = to_categorical(y, num_classes=vocab_size)

In [13]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### 2. 모델 설계

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [15]:
model = Sequential()

model.add(Embedding(vocab_size, 10, input_length = max_len - 1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Train on 11 samples
Epoch 1/200
11/11 - 1s - loss: 2.4616 - accuracy: 0.1818
Epoch 2/200
11/11 - 0s - loss: 2.4441 - accuracy: 0.2727
Epoch 3/200
11/11 - 0s - loss: 2.4266 - accuracy: 0.2727
Epoch 4/200
11/11 - 0s - loss: 2.4087 - accuracy: 0.2727
Epoch 5/200
11/11 - 0s - loss: 2.3905 - accuracy: 0.4545
Epoch 6/200
11/11 - 0s - loss: 2.3716 - accuracy: 0.4545
Epoch 7/200
11/11 - 0s - loss: 2.3522 - accuracy: 0.4545
Epoch 8/200
11/11 - 0s - loss: 2.3321 - accuracy: 0.4545
Epoch 9/200
11/11 - 0s - loss: 2.3111 - accuracy: 0.4545
Epoch 10/200
11/11 - 0s - loss: 2.2893 - accuracy: 0.4545
Epoch 11/200
11/11 - 0s - loss: 2.2665 - accuracy: 0.4545
Epoch 12/200
11/11 - 0s - loss: 2.2429 - accuracy: 0.4545
Epoch 13/200
11/11 - 0s - loss: 2.2184 - accuracy: 0.3636
Epoch 14/200
11/11 - 0s - loss: 2.1930 - accuracy: 0.3636
Epoch 15/200
11/11 - 0s - loss: 2.1670 - accuracy: 0.3636
Epoch 16/200
11/11 - 0s - loss: 2.1403 - accuracy: 0.3636
Epoch 17/200
11/11 - 0s - loss: 2.1133 - accuracy: 0.3636
Epo

Epoch 142/200
11/11 - 0s - loss: 0.4055 - accuracy: 0.9091
Epoch 143/200
11/11 - 0s - loss: 0.3992 - accuracy: 0.9091
Epoch 144/200
11/11 - 0s - loss: 0.3929 - accuracy: 0.9091
Epoch 145/200
11/11 - 0s - loss: 0.3867 - accuracy: 0.9091
Epoch 146/200
11/11 - 0s - loss: 0.3806 - accuracy: 0.9091
Epoch 147/200
11/11 - 0s - loss: 0.3746 - accuracy: 0.9091
Epoch 148/200
11/11 - 0s - loss: 0.3686 - accuracy: 0.9091
Epoch 149/200
11/11 - 0s - loss: 0.3628 - accuracy: 0.9091
Epoch 150/200
11/11 - 0s - loss: 0.3570 - accuracy: 0.9091
Epoch 151/200
11/11 - 0s - loss: 0.3513 - accuracy: 0.9091
Epoch 152/200
11/11 - 0s - loss: 0.3456 - accuracy: 0.9091
Epoch 153/200
11/11 - 0s - loss: 0.3401 - accuracy: 0.9091
Epoch 154/200
11/11 - 0s - loss: 0.3346 - accuracy: 0.9091
Epoch 155/200
11/11 - 0s - loss: 0.3292 - accuracy: 0.9091
Epoch 156/200
11/11 - 0s - loss: 0.3238 - accuracy: 0.9091
Epoch 157/200
11/11 - 0s - loss: 0.3186 - accuracy: 0.9091
Epoch 158/200
11/11 - 0s - loss: 0.3134 - accuracy: 0.90

### 모델이 정확하게 예측하는지 문장 생성 확인

In [19]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        result = model.predict_classes(encoded, verbose=0)
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    
    return sentence

In [20]:
sentence_generation(model, t, '경마장에', 4)

'경마장에 있는 말이 뛰고 있다'

In [21]:
sentence_generation(model, t, '가는', 10)

'가는 말이 고와야 오는 말이 곱다 있다 말이 곱다 있다 곱다'

### LSTM이용한 텍스트 생성

In [22]:
import pandas as pd
from string import punctuation

### 데이터 수집

In [23]:
df = pd.read_csv('./ArticlesApril2018.csv')
df.head()

articleID  articleWordCount  \
0  5adf6684068401528a2aa69b               781   
1  5adf653f068401528a2aa697               656   
2  5adf4626068401528a2aa628              2427   
3  5adf40d2068401528a2aa619               626   
4  5adf3d64068401528a2aa60f               815   

                                      byline documentType  \
0                             By JOHN BRANCH      article   
1                           By LISA FRIEDMAN      article   
2                              By PETE WELLS      article   
3  By JULIE HIRSCHFELD DAVIS and PETER BAKER      article   
4             By IAN AUSTEN and DAN BILEFSKY      article   

                                            headline  \
0  Former N.F.L. Cheerleaders’ Settlement Offer: ...   
1  E.P.A. to Unveil a New Rule. Its Effect: Less ...   
2                            The New Noma, Explained   
3                                            Unknown   
4                                            Unknown   

                                            keywords  multimedia     newDesk  \
0  ['Workplace Hazards and Violations', 'Football...          68      Sports   
1  ['Environmental Protection Agency', 'Pruitt, S...          68     Climate   
2  ['Restaurants', 'Noma (Copenhagen, Restaurant)...          66      Dining   
3  ['Macron, Emmanuel (1977- )', 'Trump, Donald J...          68  Washington   
4  ['Toronto, Ontario, Attack (April, 2018)', 'Mu...          68     Foreign   

   printPage              pubDate   sectionName  \
0          0  2018-04-24 17:16:49  Pro Football   
1          0  2018-04-24 17:11:21       Unknown   
2          0  2018-04-24 14:58:44       Unknown   
3          0  2018-04-24 14:35:57        Europe   
4          0  2018-04-24 14:21:21        Canada   

                                             snippet              source  \
0  “I understand that they could meet with us, pa...  The New York Times   
1  The agency plans to publish a new regulation T...  The New York Times   
2  What’s it like to eat at the second incarnatio...  The New York Times   
3  President Trump welcomed President Emmanuel Ma...  The New York Times   
4  Alek Minassian, 25, a resident of Toronto’s Ri...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2018/04/24/sports/foot...  
1           News  https://www.nytimes.com/2018/04/24/climate/epa...  
2           News  https://www.nytimes.com/2018/04/24/dining/noma...  
3           News  https://www.nytimes.com/2018/04/24/world/europ...  
4           News  https://www.nytimes.com/2018/04/24/world/canad...

### 1. 데이터 이해 및 전처리

In [37]:
print("열의 개수 : {}".format(len(df.columns)))
print(df.columns)

열의 개수 : 15
Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [38]:
df['headline'].isnull().values.any()

False

In [39]:
headline = []
headline.extend(list(df.headline.values))
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [40]:
print('총 샘플의 개수 : {}'.format(len(headline)))

총 샘플의 개수 : 1324


In [41]:
headline = [n for n in headline if n != 'Unknown']
print('Noise 제거 후 샘플 의 개수 : {}'.format(len(headline)))

Noise 제거 후 샘플 의 개수 : 1214


In [42]:
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [43]:
def repreprocessing(s):
    s = s.encode('utf8').decode('ascii', 'ignore')
    return ''.join(c for c in s if c not in punctuation).lower()

text = [repreprocessing(x)for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [44]:
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : {:d}'.format(vocab_size))

단어 집합의 크기 : 3494


In [46]:
sequences = list()

for line in text:
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
        
sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [47]:
index_to_word = {}
for key, value in t.word_index.items():
    index_to_word[value] = key
    
print("빈도수 상위 582번 단어 : {}".format(index_to_word[582]))

빈도수 상위 582번 단어 : offer


In [48]:
max_len = max(len(l) for l in sequences)
print("샘플의 최대 길이 : {}".format(max_len))

샘플의 최대 길이 : 24


In [49]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [50]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

In [51]:
print(X[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]


In [52]:
print(y[:3])

[ 269  371 1115]


In [53]:
y = to_categorical(y, num_classes=vocab_size)

### 2. 모델 구성 및 훈련

In [54]:
from tensorflow.keras.layers import LSTM

In [55]:
model = Sequential()

model.add(Embedding(vocab_size, 10, input_length=max_len - 1))
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Train on 7803 samples
Epoch 1/200
7803/7803 - 8s - loss: 7.6491 - accuracy: 0.0272
Epoch 2/200
7803/7803 - 6s - loss: 7.1133 - accuracy: 0.0281
Epoch 3/200
7803/7803 - 6s - loss: 6.9754 - accuracy: 0.0358
Epoch 4/200
7803/7803 - 6s - loss: 6.8515 - accuracy: 0.0405
Epoch 5/200
7803/7803 - 6s - loss: 6.7009 - accuracy: 0.0456
Epoch 6/200
7803/7803 - 6s - loss: 6.5298 - accuracy: 0.0466
Epoch 7/200
7803/7803 - 6s - loss: 6.3429 - accuracy: 0.0525
Epoch 8/200
7803/7803 - 6s - loss: 6.1442 - accuracy: 0.0559
Epoch 9/200
7803/7803 - 6s - loss: 5.9512 - accuracy: 0.0614
Epoch 10/200
7803/7803 - 6s - loss: 5.7615 - accuracy: 0.0678
Epoch 11/200
7803/7803 - 6s - loss: 5.5879 - accuracy: 0.0707
Epoch 12/200
7803/7803 - 6s - loss: 5.4232 - accuracy: 0.0764
Epoch 13/200
7803/7803 - 6s - loss: 5.2659 - accuracy: 0.0819
Epoch 14/200
7803/7803 - 6s - loss: 5.1183 - accuracy: 0.0856
Epoch 15/200
7803/7803 - 7s - loss: 4.9766 - accuracy: 0.0962
Epoch 16/200
7803/7803 - 6s - loss: 4.8405 - accuracy: 0.

Epoch 133/200
7803/7803 - 6s - loss: 0.3755 - accuracy: 0.9113
Epoch 134/200
7803/7803 - 6s - loss: 0.3689 - accuracy: 0.9146
Epoch 135/200
7803/7803 - 6s - loss: 0.3653 - accuracy: 0.9136
Epoch 136/200
7803/7803 - 6s - loss: 0.3605 - accuracy: 0.9134
Epoch 137/200
7803/7803 - 6s - loss: 0.3562 - accuracy: 0.9134
Epoch 138/200
7803/7803 - 6s - loss: 0.3547 - accuracy: 0.9138
Epoch 139/200
7803/7803 - 6s - loss: 0.3650 - accuracy: 0.9116
Epoch 140/200
7803/7803 - 6s - loss: 0.3575 - accuracy: 0.9136
Epoch 141/200
7803/7803 - 6s - loss: 0.3414 - accuracy: 0.9154
Epoch 142/200
7803/7803 - 6s - loss: 0.3355 - accuracy: 0.9152
Epoch 143/200
7803/7803 - 6s - loss: 0.3329 - accuracy: 0.9164
Epoch 144/200
7803/7803 - 6s - loss: 0.3308 - accuracy: 0.9161
Epoch 145/200
7803/7803 - 6s - loss: 0.3275 - accuracy: 0.9141
Epoch 146/200
7803/7803 - 6s - loss: 0.3262 - accuracy: 0.9146
Epoch 147/200
7803/7803 - 6s - loss: 0.3250 - accuracy: 0.9152
Epoch 148/200
7803/7803 - 6s - loss: 0.3201 - accuracy:

In [56]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=23, padding='pre')
        result = model.predict_classes(encoded, verbose=0)
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    
    return sentence

In [57]:
print(sentence_generation(model, t, 'is', 5))

is it wrong to focus on


In [58]:
print(sentence_generation(model, t, 'how', 10))

how our journalism is like a car crash wait that didnt


## 글자 단위 RNN(Char RNN)

- 입출력 단위를 단어 레벨(word-level)에서 글자 레벨(character-level)로 변경하여 RNN을 구현할 수 있다.
- 입출력 단위를 글자로 변경한 것

In [59]:
import urllib.request

In [60]:
urllib.request.urlretrieve("http://www.gutenberg.org/files/11/11-0.txt", filename="11-0.txt")
f = open('11-0.txt', 'rb')
lines = []
for line in f:
    line = line.strip()
    line = line.lower()
    line = line.decode('ascii', 'ignore')
    if len(line) > 0:
        lines.append(line)
f.close

<function BufferedReader.close>

In [61]:
lines[:5]

['the project gutenberg ebook of alices adventures in wonderland, by lewis carroll',
 'this ebook is for the use of anyone anywhere at no cost and with',
 'almost no restrictions whatsoever.  you may copy it, give it away or',
 're-use it under the terms of the project gutenberg license included',
 'with this ebook or online at www.gutenberg.org']

In [62]:
text = ' '.join(lines)
print('문자열의 길이 또는 총 글자의 개수 : {}'.format(len(text)))

문자열의 길이 또는 총 글자의 개수 : 159612


In [63]:
print(text[:200])

the project gutenberg ebook of alices adventures in wonderland, by lewis carroll this ebook is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever.  you may copy it, g


In [64]:
char_vocab = sorted(list(set(text)))
vocab_size = len(char_vocab)
print("글자 집합의 크기 : {}".format(vocab_size))

글자 집합의 크기 : 57


In [65]:
char_to_index = dict((c, i) for i, c in enumerate(char_vocab))
print(char_to_index)

{' ': 0, '!': 1, '"': 2, '#': 3, '$': 4, '%': 5, "'": 6, '(': 7, ')': 8, '*': 9, ',': 10, '-': 11, '.': 12, '/': 13, '0': 14, '1': 15, '2': 16, '3': 17, '4': 18, '5': 19, '6': 20, '7': 21, '8': 22, '9': 23, ':': 24, ';': 25, '?': 26, '@': 27, '[': 28, ']': 29, '_': 30, 'a': 31, 'b': 32, 'c': 33, 'd': 34, 'e': 35, 'f': 36, 'g': 37, 'h': 38, 'i': 39, 'j': 40, 'k': 41, 'l': 42, 'm': 43, 'n': 44, 'o': 45, 'p': 46, 'q': 47, 'r': 48, 's': 49, 't': 50, 'u': 51, 'v': 52, 'w': 53, 'x': 54, 'y': 55, 'z': 56}


In [66]:
index_to_char = {}
for key, value in char_to_index.items():
    index_to_char[value] = key

In [67]:
seq_length = 60
n_samples = int(np.floor((len(text) - 1) / seq_length))
print("문장 샘플의 수 : {}".format(n_samples))

문장 샘플의 수 : 2660


In [82]:
train_X = []
train_y = []

for i in range(n_samples):
    X_sample = text[i * seq_length : (i + 1) * seq_length]
    X_encoded = [char_to_index[c] for c in X_sample]
    train_X.append(X_encoded)
    
    y_sample = text[i * seq_length : (i + 1) * seq_length]
    y_encoded = [char_to_index[c] for c in y_sample]
    train_y.append(y_encoded)

In [83]:
print(train_X[0])

[50, 38, 35, 0, 46, 48, 45, 40, 35, 33, 50, 0, 37, 51, 50, 35, 44, 32, 35, 48, 37, 0, 35, 32, 45, 45, 41, 0, 45, 36, 0, 31, 42, 39, 33, 35, 49, 0, 31, 34, 52, 35, 44, 50, 51, 48, 35, 49, 0, 39, 44, 0, 53, 45, 44, 34, 35, 48, 42, 31]


In [84]:
print(train_y[0])

[50, 38, 35, 0, 46, 48, 45, 40, 35, 33, 50, 0, 37, 51, 50, 35, 44, 32, 35, 48, 37, 0, 35, 32, 45, 45, 41, 0, 45, 36, 0, 31, 42, 39, 33, 35, 49, 0, 31, 34, 52, 35, 44, 50, 51, 48, 35, 49, 0, 39, 44, 0, 53, 45, 44, 34, 35, 48, 42, 31]


In [85]:
print(train_X[1])

[44, 34, 10, 0, 32, 55, 0, 42, 35, 53, 39, 49, 0, 33, 31, 48, 48, 45, 42, 42, 0, 50, 38, 39, 49, 0, 35, 32, 45, 45, 41, 0, 39, 49, 0, 36, 45, 48, 0, 50, 38, 35, 0, 51, 49, 35, 0, 45, 36, 0, 31, 44, 55, 45, 44, 35, 0, 31, 44, 55]


In [86]:
print(train_y[1])

[44, 34, 10, 0, 32, 55, 0, 42, 35, 53, 39, 49, 0, 33, 31, 48, 48, 45, 42, 42, 0, 50, 38, 39, 49, 0, 35, 32, 45, 45, 41, 0, 39, 49, 0, 36, 45, 48, 0, 50, 38, 35, 0, 51, 49, 35, 0, 45, 36, 0, 31, 44, 55, 45, 44, 35, 0, 31, 44, 55]


In [87]:
train_X = to_categorical(train_X)
train_y = to_categorical(train_y)

In [88]:
print('train_X의 크기(shape) : {}'.format(train_X.shape))
print('train_y의 크기(shape) : {}'.format(train_y.shape))

train_X의 크기(shape) : (2660, 60, 57)
train_y의 크기(shape) : (2660, 60, 57)


### 모델 설계 및 훈련

In [89]:
from tensorflow.keras.layers import TimeDistributed

In [ ]:
model = Sequential()

model.add(LSTM(256, input_shape=(None, train_X.shape[2]), return_sequences=True))
model.add(LSTM(256, return_sequences=True))
model.add(TimeDistributed(Dense(vocab_size, activation='softmax')))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(train_X, train_y, epochs=80, verbose=2)

Train on 2660 samples
Epoch 1/80
2660/2660 - 33s - loss: 2.9468 - accuracy: 0.2187
Epoch 2/80
2660/2660 - 32s - loss: 0.8925 - accuracy: 0.8592
Epoch 3/80
2660/2660 - 33s - loss: 0.1389 - accuracy: 0.9895
Epoch 4/80
2660/2660 - 34s - loss: 0.0620 - accuracy: 0.9971
Epoch 5/80
2660/2660 - 35s - loss: 0.0354 - accuracy: 0.9987
Epoch 6/80
2660/2660 - 36s - loss: 0.0222 - accuracy: 0.9988
Epoch 7/80
2660/2660 - 37s - loss: 0.0148 - accuracy: 0.9992
Epoch 8/80
2660/2660 - 38s - loss: 0.0103 - accuracy: 0.9994
Epoch 9/80
2660/2660 - 36s - loss: 0.0075 - accuracy: 0.9996
Epoch 10/80
2660/2660 - 36s - loss: 0.0056 - accuracy: 0.9998
Epoch 11/80
2660/2660 - 35s - loss: 0.0043 - accuracy: 0.9998
Epoch 12/80
2660/2660 - 36s - loss: 0.0034 - accuracy: 0.9999
Epoch 13/80
2660/2660 - 36s - loss: 0.0027 - accuracy: 0.9999
Epoch 14/80
2660/2660 - 35s - loss: 0.0022 - accuracy: 0.9999
Epoch 15/80
2660/2660 - 36s - loss: 0.0018 - accuracy: 0.9999
Epoch 16/80
2660/2660 - 37s - loss: 0.0015 - accuracy: 1.

In [ ]:
def sentence_generation(model, length):
    ix = [np.random.randint(vocab_size)]
    y_char = [index_to_char[ix[-1]]]
    print(ix[-1], '번 글자', y_char[-1], '로 예측을 시작!')
    X = np.aeros((1, length, vocab_size))
    for _ in range(length):
        X[0][i][ix[-1]] = 1
        print(index_to_char[ix[-1]], end="")
        ix = np.argmax(model.predict(X[:, :i+1, :])[0], 1)
        y_char.append(index_to_char[ix[-1]])
    return ('').join(y_char)

In [ ]:
sentence_generation(model, 100)